    export const MARKET_SYMBOLS = {
    NSE: [
        "RELIANCE.NS",
        "TCS.NS",
        "INFY.NS",
        "HDFCBANK.NS",
        "ICICIBANK.NS",
        "SBIN.NS",
        "BHARTIARTL.NS",
        "ITC.NS",
        "LT.NS",
        "HINDUNILVR.NS",
    ],

    NASDAQ: [
        "AAPL",
        "MSFT",
        "NVDA",
        "AMZN",
        "META",
        "GOOGL",
        "TSLA",
        "NFLX",
        "AMD",
        "INTC",
    ],

    NYSE: [
        "BRK-B",
        "JPM",
        "V",
        "WMT",
        "JNJ",
        "PG",
        "XOM",
        "KO",
        "MCD",
        "DIS",
    ],

    LSE: [
        "SHEL.L",
        "AZN.L",
        "BP.L",
        "HSBA.L",
        "ULVR.L",
        "RIO.L",
        "VOD.L",
        "GSK.L",
        "BARC.L",
        "LLOY.L",
    ],

    TSE: [
        "7203.T",
        "6758.T",
        "9984.T",
        "8306.T",
        "6861.T",
        "9432.T",
        "8035.T",
        "6501.T",
        "8058.T",
        "7974.T",
    ],

    HKEX: [
        "0700.HK",
        "9988.HK",
        "1299.HK",
        "0005.HK",
        "3690.HK",
        "9618.HK",
        "2318.HK",
        "1810.HK",
        "0388.HK",
        "0941.HK",
    ],
    };